modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="noprivateorprotected"
version="1.0.0"
displayName="noPrivateOrProtected"
credits="Created using mod maker MCreator(???) - https://mcreator.net/about"
displayURL="https://space.bilibili.com/486236048"
authors="apphhzp, MCreator"

[[dependencies.noprivateorprotected]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




